const translations = {
    th: {
        'greeting.morning': 'สวัสดีตอนเช้า',
        'greeting.noon': 'สวัสดีตอนเที่ยง',
        'greeting.afternoon': 'สวัสดีตอนบ่าย',
        'greeting.evening': 'สวัสดีตอนเย็น',
        'greeting.night': 'ราตรีสวัสดิ์',
        'tab.booking': 'จองคิว',
        'tab.history': 'ข้อมูลการนัดหมาย',
        'step1.title': 'เลือกบริการ',
        'step1.button': 'ถัดไป',
        'step2.dateLabel': 'เลือกวันที่',
        'step2.timeLabel': 'เลือกเวลา',
        'step2.placeholder': 'ยังไม่ได้เลือกวัน',
        'step2.loading': 'โปรดรอสักครู่...',
        'step2.error': 'ไม่สามารถโหลดเวลาได้',
        'step2.noTime': 'ไม่มีช่วงเวลาว่าง',
        'step2.back': 'ย้อนกลับ',
        'step2.next': 'ถัดไป',
        'step3.title': 'ข้อมูลติดต่อ',
        'step3.firstNamePlaceholder': 'ชื่อจริง',
        'step3.lastNamePlaceholder': 'นามสกุล',
        'step3.phonePlaceholder': 'เบอร์ติดต่อ',
        'step3.idCardOrSocialPlaceholder': 'เลขที่บัตรประชาชน/เลขที่ประกันสังคม',
        'step3.diseaseAllergyPlaceholder': 'โรคประจำตัว/อาการแพ้ (ถ้ามี)',
        'step3.notePlaceholder': 'หมายเหตุ (ถ้ามี)',
        'step3.back': 'ย้อนกลับ',
        'step3.next': 'ถัดไป',
        'step4.title': 'ตรวจสอบข้อมูล',
        'step4.serviceLabel': 'บริการ:',
        'step4.dateLabel': 'วันที่:',
        'step4.timeLabel': 'เวลา:',
        'step4.nameLabel': 'ชื่อ-นามสกุล:',
        'step4.phoneLabel': 'เบอร์:',
        'step4.idCardOrSocialLabel': 'เลขบัตร/ประกัน:',
        'step4.diseaseAllergyLabel': 'โรค/แพ้:',
        'step4.noteLabel': 'หมายเหตุ:',
        'step4.back': 'ย้อนกลับ',
        'step4.confirm': 'ยืนยันการจอง',
        'popup.close': 'ปิด',
        'popup.calendarError': 'ไม่สามารถโหลดปฏิทินได้',
        'popup.serviceError': 'ไม่สามารถโหลดบริการได้',
        'popup.timeError': 'ไม่สามารถโหลดเวลาได้',
        'popup.serviceNeeded': 'กรุณาเลือกบริการอย่างน้อย 1 รายการ',
        'popup.dateNeeded': 'กรุณาเลือกวันที่',
        'popup.timeNeeded': 'กรุณาเลือกเวลา',
        'popup.firstNameNeeded': 'กรุณากรอกชื่อจริง',
        'popup.lastNameNeeded': 'กรุณากรอกนามสกุล',
        'popup.idCardOrSocialNeeded': 'กรุณากรอกเลขที่บัตรประชาชน/เลขที่ประกันสังคม',
        'popup.phoneNeeded': 'กรุณากรอกเบอร์ติดต่อ',
        'popup.phoneFormatError': 'รูปแบบเบอร์ติดต่อไม่ถูกต้อง',
        'popup.submitError': 'ส่งข้อมูลไม่สำเร็จ',
        'popup.bookingSuccess': 'การจองสำเร็จแล้ว!',
        'calendar.holiday': 'หยุด',
        'service.noService': 'ไม่พบรายการบริการ',
        // Service translations - Dental Services
        'service.ขูดหินปูน': 'ขูดหินปูน',
        'service.ตรวจฟัน': 'ตรวจฟันทั่วไป',
        'service.อุดฟัน': 'อุดฟัน',
        'service.ถอนฟัน': 'ถอนฟัน',
        'service.รักษารากฟัน': 'รักษารากฟัน',
        'service.ทำฟันปลอม': 'ทำฟันปลอม',
        'service.จัดฟัน': 'จัดฟัน',
        'service.ฟอกสีฟัน': 'ฟอกสีฟัน',
        'service.ครอบฟัน': 'ครอบฟัน/วีเนียร์',
        'service.ศัลยกรรมช่องปาก': 'ศัลยกรรมช่องปาก',
        'service.ทำความสะอาดฟัน': 'ทำความสะอาดฟัน',
        'service.รอยยิ้มใหม่': 'ออกแบบรอยยิ้มใหม่',
        'flex.header': 'ยืนยันการจองสำเร็จ',
        'flex.altText': 'รายละเอียดการจองของคุณ',
        'flex.serviceLabel': 'บริการ',
        'flex.dateLabel': 'วันที่',
        'flex.timeLabel': 'เวลา',
        'flex.nameLabel': 'ชื่อ',
        'flex.phoneLabel': 'เบอร์',
        'flex.idCardOrSocialLabel': 'เลขบัตร/ประกัน',
        'flex.diseaseAllergyLabel': 'โรค/แพ้',
        'flex.noteLabel': 'หมายเหตุ',
    // --- History page ---
    'history.title': 'รายการนัดหมายของคุณ',
    'history.loading': 'กำลังโหลดข้อมูล...',
    'history.nodata': 'ไม่พบข้อมูล',
    'history.col.name': 'ชื่อ-นามสกุล',
    'history.col.date': 'วันที่',
    'history.col.status': 'สถานะ',
    'history.col.view': 'ดู',
    'history.status.all': 'ทั้งหมด',
    'history.status.pending': 'รอการยืนยัน',
    'history.status.confirmed': 'ยืนยันแล้ว',
    'history.status.cancelled': 'ยกเลิก',
    'history.status.completed': 'เสร็จสิ้น',
    'history.sort.latest': 'วันที่ล่าสุด',
    'history.sort.oldest': 'วันที่เก่าสุด',
    'history.view': 'ดู',
    'history.detail.name': 'ชื่อ:',
    'history.detail.phone': 'เบอร์โทร:',
    'history.detail.id': 'เลขบัตร/ประกัน:',
    'history.detail.disease': 'โรค/แพ้:',
    'history.detail.service': 'บริการ:',
    'history.detail.date': 'วันที่:',
    'history.detail.time': 'เวลา:',
    'history.detail.note': 'หมายเหตุ:',
    'history.detail.status': 'สถานะ:',
    'history.confirm': 'ยืนยัน',
    'history.cancel': 'ยกเลิก',
    'history.confirmQ': 'ยืนยันรายการนี้?',
    'history.cancelQ': 'ยกเลิกรายการนี้?',
    'history.success': 'ดำเนินการสำเร็จ',
    'history.error': 'เกิดข้อผิดพลาด',
    'confirm.title': 'จัดการนัดหมาย',
    'confirm.success': 'สำเร็จ!',
    'confirm.error': 'เกิดข้อผิดพลาด',
    'confirm.loading': 'กำลังดำเนินการ...',
    'confirm.resultSuccess': 'ดำเนินการเรียบร้อยแล้ว',
    'confirm.resultConfirm': 'ยืนยันการนัดหมายสำเร็จแล้ว',
    'confirm.resultCancel': 'ยกเลิกการนัดหมายสำเร็จแล้ว',
    'confirm.btn.confirm': 'ยืนยันนัดหมาย',
    'confirm.btn.cancel': 'ยกเลิก',
    'confirm.btn.close': 'ปิด',
    'confirm.label.name': 'ชื่อผู้จอง:',
    'confirm.label.service': 'บริการ:',
    'confirm.label.price': 'ราคา:',
    'confirm.label.date': 'วันที่:',
    'confirm.label.time': 'เวลา:'
    },
    en: {
        'greeting.morning': 'Good morning',
        'greeting.noon': 'Good day',
        'greeting.afternoon': 'Good afternoon',
        'greeting.evening': 'Good evening',
        'greeting.night': 'Good night',
        'tab.booking': 'Booking',
        'tab.history': 'Appointment Information',
        'step1.title': 'Select Service',
        'step1.button': 'Next',
        'step2.dateLabel': 'Select Date',
        'step2.timeLabel': 'Select Time',
        'step2.placeholder': 'No date selected',
        'step2.loading': 'Please wait...',
        'step2.error': 'Failed to load times',
        'step2.noTime': 'No available slots',
        'step2.back': 'Back',
        'step2.next': 'Next',
        'step3.title': 'Contact Information',
        'step3.firstNamePlaceholder': 'First Name',
        'step3.lastNamePlaceholder': 'Last Name',
        'step3.phonePlaceholder': 'Phone Number',
        'step3.idCardOrSocialPlaceholder': 'National ID/Social Security Number',
        'step3.diseaseAllergyPlaceholder': 'Disease/Allergy (optional)',
        'step3.notePlaceholder': 'Notes (optional)',
        'step3.back': 'Back',
        'step3.next': 'Next',
        'step4.title': 'Review Booking',
        'step4.serviceLabel': 'Service:',
        'step4.dateLabel': 'Date:',
        'step4.timeLabel': 'Time:',
        'step4.nameLabel': 'Full Name:',
        'step4.phoneLabel': 'Phone:',
        'step4.idCardOrSocialLabel': 'ID/Social Security:',
        'step4.diseaseAllergyLabel': 'Disease/Allergy:',
        'step4.noteLabel': 'Note:',
        'step4.back': 'Back',
        'step4.confirm': 'Confirm Booking',
        'popup.close': 'Close',
        'popup.calendarError': 'Failed to load calendar.',
        'popup.serviceError': 'Failed to load services.',
        'popup.timeError': 'Failed to load available times.',
        'popup.serviceNeeded': 'Please select at least one service.',
        'popup.dateNeeded': 'Please select a date.',
        'popup.timeNeeded': 'Please select a time.',
        'popup.firstNameNeeded': 'Please enter your first name.',
        'popup.lastNameNeeded': 'Please enter your last name.',
        'popup.idCardOrSocialNeeded': 'Please enter your ID/Social Security number.',
        'popup.phoneNeeded': 'Please enter your phone number.',
        'popup.phoneFormatError': 'Invalid phone number format.',
        'popup.submitError': 'Booking submission failed.',
        'popup.bookingSuccess': 'Booking successful!',
        'calendar.holiday': 'Holiday',
        'service.noService': 'No services found',
        // Service translations - Dental Services
        'service.ขูดหินปูน': 'Scaling & Polishing',
        'service.ตรวจฟัน': 'General Check-up',
        'service.อุดฟัน': 'Dental Filling',
        'service.ถอนฟัน': 'Tooth Extraction',
        'service.รักษารากฟัน': 'Root Canal Treatment',
        'service.ทำฟันปลอม': 'Dentures',
        'service.จัดฟัน': 'Orthodontics/Braces',
        'service.ฟอกสีฟัน': 'Teeth Whitening',
        'service.ครอบฟัน': 'Crown/Veneer',
        'service.ศัลยกรรมช่องปาก': 'Oral Surgery',
        'service.ทำความสะอาดฟัน': 'Dental Cleaning',
        'service.รอยยิ้มใหม่': 'Smile Makeover',
        'flex.header': 'Booking Confirmed',
        'flex.altText': 'Your booking details',
        'flex.serviceLabel': 'Service',
        'flex.dateLabel': 'Date',
        'flex.timeLabel': 'Time',
        'flex.nameLabel': 'Name',
        'flex.phoneLabel': 'Phone',
        'flex.idCardOrSocialLabel': 'ID/Social Security',
        'flex.diseaseAllergyLabel': 'Disease/Allergy',
        'flex.noteLabel': 'Note',
    // --- History page ---
    'history.title': 'Your Appointments',
    'history.loading': 'Loading data...',
    'history.nodata': 'No data found',
    'history.col.name': 'Name',
    'history.col.date': 'Date',
    'history.col.status': 'Status',
    'history.col.view': 'View',
    'history.status.all': 'All',
    'history.status.pending': 'Pending',
    'history.status.confirmed': 'Confirmed',
    'history.status.cancelled': 'Cancelled',
    'history.status.completed': 'Completed',
    'history.sort.latest': 'Latest Date',
    'history.sort.oldest': 'Oldest Date',
    'history.view': 'View',
    'history.detail.name': 'Name:',
    'history.detail.phone': 'Phone:',
    'history.detail.id': 'ID/Social:',
    'history.detail.disease': 'Disease/Allergy:',
    'history.detail.service': 'Service:',
    'history.detail.date': 'Date:',
    'history.detail.time': 'Time:',
    'history.detail.note': 'Note:',
    'history.detail.status': 'Status:',
    'history.confirm': 'Confirm',
    'history.cancel': 'Cancel',
    'history.confirmQ': 'Confirm this item?',
    'history.cancelQ': 'Cancel this item?',
    'history.success': 'Operation successful',
    'history.error': 'Error occurred',
    'confirm.title': 'Manage Appointment',
    'confirm.success': 'Success!',
    'confirm.error': 'Error',
    'confirm.loading': 'Processing...',
    'confirm.resultSuccess': 'Operation completed',
    'confirm.resultConfirm': 'Appointment confirmed',
    'confirm.resultCancel': 'Appointment cancelled',
    'confirm.btn.confirm': 'Confirm',
    'confirm.btn.cancel': 'Cancel',
    'confirm.btn.close': 'Close',
    'confirm.label.name': 'Name:',
    'confirm.label.service': 'Service:',
    'confirm.label.price': 'Price:',
    'confirm.label.date': 'Date:',
    'confirm.label.time': 'Time:'
    },
    my: {
        'greeting.morning': 'မင်္ဂလာနံနက်ခင်းပါ',
        'greeting.noon': 'မင်္ဂလာနေ့လည်ခင်းပါ',
        'greeting.afternoon': 'မင်္ဂလာနေ့လည်ခင်းပါ',
        'greeting.evening': 'မင်္ဂလာညနေခင်းပါ',
        'greeting.night': 'ကောင်းသောညပါ',
        'tab.booking': 'အပ်ချိန်းတင်ရန်',
        'tab.history': 'ချိန်းဆိုမှုအချက်အလက်',
        'step1.title': 'ဝန်ဆောင်မှုရွေးချယ်ပါ',
        'step1.button': 'ရှေ့သို့',
        'step2.dateLabel': 'နေ့ရက်ရွေးချယ်ပါ',
        'step2.timeLabel': 'အချိန်ရွေးချယ်ပါ',
        'step2.placeholder': 'နေ့ရက်မရွေးချယ်ရသေးပါ',
        'step2.loading': 'ခဏစောင့်ပေးပါ...',
        'step2.error': 'အချိန်တင်မရနိုင်ပါ',
        'step2.noTime': 'အချိန်မရှိပါ',
        'step2.back': 'နောက်သို့',
        'step2.next': 'ရှေ့သို့',
        'step3.title': 'ဆက်သွယ်ရန်အချက်အလက်',
        'step3.firstNamePlaceholder': 'နာမည်',
        'step3.lastNamePlaceholder': 'အမျိုးအမည်',
        'step3.phonePlaceholder': 'ဖုန်းနံပါတ်',
        'step3.idCardOrSocialPlaceholder': 'နိုင်ငံသား/လူမှုဖူလုံရေးနံပါတ်',
        'step3.diseaseAllergyPlaceholder': 'ရောဂါ/အာဟာရမတည့်မှု (ရှိပါက)',
        'step3.notePlaceholder': 'မှတ်ချက် (ရှိပါက)',
        'step3.back': 'နောက်သို့',
        'step3.next': 'ရှေ့သို့',
        'step4.title': 'အချက်အလက်ပြန်စစ်ပါ',
        'step4.serviceLabel': 'ဝန်ဆောင်မှု:',
        'step4.dateLabel': 'နေ့ရက်:',
        'step4.timeLabel': 'အချိန်:',
        'step4.nameLabel': 'နာမည်-အမျိုးအမည်:',
        'step4.phoneLabel': 'ဖုန်းနံပါတ်:',
        'step4.idCardOrSocialLabel': 'ID/လူမှုဖူလုံရေး:',
        'step4.diseaseAllergyLabel': 'ရောဂါ/အာဟာရမတည့်မှု:',
        'step4.noteLabel': 'မှတ်ချက်:',
        'step4.back': 'နောက်သို့',
        'step4.confirm': 'အတည်ပြုရန်',
        'popup.close': 'ပိတ်မည်',
        'popup.calendarError': 'ပြက္ခဒိန်တင်မရနိုင်ပါ',
        'popup.serviceError': 'ဝန်ဆောင်မှုတင်မရနိုင်ပါ',
        'popup.timeError': 'ရရှိနိုင်သောအချိန်တင်မရနိုင်ပါ',
        'popup.serviceNeeded': 'အနည်းဆုံးဝန်ဆောင်မှုတစ်ခုရွေးချယ်ပါ',
        'popup.dateNeeded': 'နေ့ရက်ရွေးချယ်ပါ',
        'popup.timeNeeded': 'အချိန်ရွေးချယ်ပါ',
        'popup.firstNameNeeded': 'ကျေးဇူးပြု၍ နာမည်ထည့်ပါ',
        'popup.lastNameNeeded': 'ကျေးဇူးပြု၍ အမျိုးအမည်ထည့်ပါ',
        'popup.idCardOrSocialNeeded': 'ကျေးဇူးပြု၍ ID/လူမှုဖူလုံရေးနံပါတ်ထည့်ပါ',
        'popup.phoneNeeded': 'ကျေးဇူးပြု၍ ဖုန်းနံပါတ်ထည့်ပါ',
        'popup.phoneFormatError': 'ဖုန်းနံပါတ်ပုံစံမမှန်ကန်ပါ',
        'popup.submitError': 'တင်ပြမှုမအောင်မြင်ပါ',
        'popup.bookingSuccess': 'ဘိုကင်အောင်မြင်ပါပြီ!',
        'calendar.holiday': 'အားလပ်ရက်',
        'service.noService': 'ဝန်ဆောင်မှုမရှိပါ',
        // Service translations - Dental Services
        'service.ขูดหินปูน': 'သွားကျောက်ရှင်းလင်းခြင်း',
        'service.ตรวจฟัน': 'သွားစစ်ဆေးခြင်း',
        'service.อุดฟัน': 'သွားဖောက်ခြင်း',
        'service.ถอนฟัน': 'သွားနုတ်ခြင်း',
        'service.รักษารากฟัน': 'သွားအမြစ်ကုသခြင်း',
        'service.ทำฟันปลอม': 'သွားတုလုပ်ခြင်း',
        'service.จัดฟัน': 'သွားညှိခြင်း',
        'service.ฟอกสีฟัน': 'သွားဖြူခြင်း',
        'service.ครอบฟัน': 'သွားဖုံးအုပ်ခြင်း',
        'service.ศัลยกรรมช่องปาก': 'ခံတွင်းခွဲစိတ်ကုသခြင်း',
        'service.ทำความสะอาดฟัน': 'သွားသန့်ရှင်းခြင်း',
        'service.รอยยิ้มใหม่': 'ပြုံးရွှင်မှုအသစ်ဒီဇိုင်း',
        'flex.header': '📋 ကြိုတင်မှာယူမှု အသေးစိတ်',
        'flex.altText': 'သင်၏ဘိုကင်အသေးစိတ်',
        'flex.serviceLabel': 'ဝန်ဆောင်မှု',
        'flex.dateLabel': 'နေ့ရက်',
        'flex.timeLabel': 'အချိန်',
        'flex.nameLabel': 'အမည်',
        'flex.phoneLabel': 'ဖုန်းနံပါတ်',
        'flex.idCardOrSocialLabel': 'ID/လူမှုဖူလုံရေး',
        'flex.diseaseAllergyLabel': 'ရောဂါ/မတည့်မှု',
        'flex.noteLabel': 'မှတ်ချက်',
    // --- History page ---
    'history.title': 'သင့်ရဲ့ချိန်းဆိုမှုများ',
    'history.loading': 'ဒေတာတင်နေသည်...',
    'history.nodata': 'ဒေတာမရှိပါ',
    'history.col.name': 'အမည်',
    'history.col.date': 'ရက်စွဲ',
    'history.col.status': 'အခြေအနေ',
    'history.col.view': 'ကြည့်ရန်',
    'history.status.all': 'အားလုံး',
    'history.status.pending': 'စောင့်ဆိုင်းနေသည်',
    'history.status.confirmed': 'အတည်ပြုပြီး',
    'history.status.cancelled': 'ဖျက်သိမ်းပြီး',
    'history.status.completed': 'ပြီးဆုံးသည်',
    'history.sort.latest': 'နောက်ဆုံးရက်',
    'history.sort.oldest': 'အဟောင်းဆုံးရက်',
    'history.view': 'ကြည့်ရန်',
    'history.detail.name': 'အမည်:',
    'history.detail.phone': 'ဖုန်း:',
    'history.detail.id': 'ID/လူမှု:',
    'history.detail.disease': 'ရောဂါ/မတည့်မှု:',
    'history.detail.service': 'ဝန်ဆောင်မှု:',
    'history.detail.date': 'ရက်စွဲ:',
    'history.detail.time': 'အချိန်:',
    'history.detail.note': 'မှတ်ချက်:',
    'history.detail.status': 'အခြေအနေ:',
    'history.confirm': 'အတည်ပြုပါ',
    'history.cancel': 'ဖျက်ပါ',
    'history.confirmQ': 'ဤအချက်အလက်ကိုအတည်ပြုမည်လား?',
    'history.cancelQ': 'ဤအချက်အလက်ကိုဖျက်မည်လား?',
    'history.success': 'အောင်မြင်ပါသည်',
    'history.error': 'အမှားအယွင်း',

    },
  // --- Cambodian (km) ---
  km: {
    'greeting.morning': 'អរុណសួស្តី',
    'greeting.noon': 'ទិវាសួស្តី',
    'greeting.afternoon': 'សាយណ្ហសួស្តី',
    'greeting.evening': 'សាយណ្ហសួស្តី',
    'greeting.night': 'រាត្រីសួស្តី',
    'tab.booking': 'ការកក់',
    'tab.history': 'ព័ត៌មានអំពីការណាត់ជួប',
    'step1.title': 'ជ្រើសរើសសេវាកម្ម',
    'step1.button': 'បន្ទាប់',
    'step2.dateLabel': 'ជ្រើសរើសកាលបរិច្ឆេទ',
    'step2.timeLabel': 'ជ្រើសរើសពេលវេលា',
    'step2.placeholder': 'មិនទាន់ជ្រើសរើសកាលបរិច្ឆេទ',
    'step2.loading': 'សូមរង់ចាំ...',
    'step2.error': 'មិនអាចផ្ទុកពេលវេលាបានទេ',
    'step2.noTime': 'គ្មានម៉ោងទំនេរ',
    'step2.back': 'ត្រលប់',
    'step2.next': 'បន្ទាប់',
    'step3.title': 'ព័ត៌មានទំនាក់ទំនង',
    'step3.firstNamePlaceholder': 'ឈ្មោះ',
    'step3.lastNamePlaceholder': 'នាមត្រកូល',
    'step3.phonePlaceholder': 'លេខទូរស័ព្ទ',
    'step3.idCardOrSocialPlaceholder': 'លេខអត្តសញ្ញាណប័ណ្ណ/លេខសន្តិសុខសង្គម',
    'step3.diseaseAllergyPlaceholder': 'ជំងឺ/អាឡែស៊ី (បើមាន)',
    'step3.notePlaceholder': 'កំណត់ចំណាំ (បើមាន)',
    'step3.back': 'ត្រលប់',
    'step3.next': 'បន្ទាប់',
    'step4.title': 'ពិនិត្យមើលข้อมูล',
    'step4.serviceLabel': 'សេវាកម្ម:',
    'step4.dateLabel': 'កាលបរិច្ឆេទ:',
    'step4.timeLabel': 'ពេលវេលា:',
    'step4.nameLabel': 'ឈ្មោះពេញ:',
    'step4.phoneLabel': 'ទូរស័ព្ទ:',
    'step4.idCardOrSocialLabel': 'អត្តសញ្ញាណប័ណ្ណ/សន្តិសុខសង្គម:',
    'step4.diseaseAllergyLabel': 'ជំងឺ/អាឡែស៊ី:',
    'step4.noteLabel': 'កំណត់ចំណាំ:',
    'step4.back': 'ត្រលប់',
    'step4.confirm': 'បញ្ជាក់ការកក់',
    'popup.close': 'បិទ',
    'popup.calendarError': 'មិនអាចផ្ទុកប្រតិទិនបានទេ',
    'popup.serviceError': 'មិនអាចផ្ទុកសេវាកម្មបានទេ',
    'popup.timeError': 'មិនអាចផ្ទុកពេលវេលាទំនេរបានទេ',
    'popup.serviceNeeded': 'សូមជ្រើសរើសសេវាកម្មយ៉ាងហោចណាស់មួយ',
    'popup.dateNeeded': 'សូមជ្រើសរើសកាលបរិច្ឆេទ',
    'popup.timeNeeded': 'សូមជ្រើសរើសពេលវេលា',
    'popup.firstNameNeeded': 'សូមបញ្ចូលឈ្មោះរបស់អ្នក',
    'popup.lastNameNeeded': 'សូមបញ្ចូលនាមត្រកូលរបស់អ្នក',
    'popup.idCardOrSocialNeeded': 'សូមបញ្ចូលលេខអត្តសញ្ញាណប័ណ្ណ/សន្តិសុខសង្គម',
    'popup.phoneNeeded': 'សូមបញ្ចូលលេខទូរស័ព្ទរបស់អ្នក',
    'popup.phoneFormatError': 'ទម្រង់លេខទូរស័ព្ទមិនត្រឹមត្រូវ',
    'popup.submitError': 'ការបញ្ជូនការកក់បានបរាជ័យ',
    'popup.bookingSuccess': 'ការកក់បានជោគជ័យ!',
    'calendar.holiday': 'ថ្ងៃឈប់សម្រាក',
    'service.noService': 'រកមិនឃើញសេវាកម្ម',
    // Service translations - Dental Services
    'service.ขูดหินปูน': 'កោសកំបោរ និង​ដុសខាត់',
    'service.ตรวจฟัน': 'ពិនិត្យសុខភាពមាត់ធ្មេញទូទៅ',
    'service.อุดฟัน': 'ត្បារធ្មេញ',
    'service.ถอนฟัน': 'ដកធ្មេញ',
    'service.รักษารากฟัน': 'ព្យាបាលឫសធ្មេញ',
    'service.ทำฟันปลอม': 'ធ្មេញសិប្បនិម្មិត',
    'service.จัดฟัน': 'ពត់ធ្មេញ',
    'service.ฟอกสีฟัน': 'ធ្វើឲ្យធ្មេញស',
    'service.ครอบฟัน': 'ស្រោមធ្មេញ/វីនៀ',
    'service.ศัลยกรรมช่องปาก': 'វះកាត់មាត់ធ្មេញ',
    'service.ทำความสะอาดฟัน': 'សម្អាតធ្មេញ',
    'service.รอยยิ้มใหม่': 'កែ​សម្ផស្ស​รอยยิ้ม',
    'flex.header': 'ការកក់ត្រូវបានបញ្ជាក់',
    'flex.altText': 'ព័ត៌មានលម្អិតអំពីការកក់របស់អ្នក',
    'flex.serviceLabel': 'សេវាកម្ម',
    'flex.dateLabel': 'កាលបរិច្ឆេទ',
    'flex.timeLabel': 'ពេលវេលា',
    'flex.nameLabel': 'ឈ្មោះ',
    'flex.phoneLabel': 'ទូរស័ព្ទ',
    'flex.idCardOrSocialLabel': 'អត្តសញ្ញាណប័ណ្ណ/សន្តិសុខសង្គម',
    'flex.diseaseAllergyLabel': 'ជំងឺ/អាឡែស៊ី',
    'flex.noteLabel': 'កំណត់ចំណាំ',
    // --- History page ---
    'history.title': 'ការណាត់ជួបរបស់អ្នក',
    'history.loading': 'កំពុងផ្ទុកទិន្នន័យ...',
    'history.nodata': 'រកមិនឃើញទិន្នន័យ',
    'history.col.name': 'ឈ្មោះ',
    'history.col.date': 'កាលបរិច្ឆេទ',
    'history.col.status': 'ស្ថានភាព',
    'history.col.view': 'មើល',
    'history.status.all': 'ទាំងអស់',
    'history.status.pending': 'កំពុងរង់ចាំ',
    'history.status.confirmed': 'បានបញ្ជាក់',
    'history.status.cancelled': 'បានបោះបង់',
    'history.status.completed': 'បានបញ្ចប់',
    'history.sort.latest': 'កាលបរិច្ឆេទล่าสุด',
    'history.sort.oldest': 'កាលបរិច្ឆេទเก่าสุด',
    'history.view': 'មើល',
    'history.detail.name': 'ឈ្មោះ:',
    'history.detail.phone': 'ទូរស័ព្ទ:',
    'history.detail.id': 'អត្តសញ្ញាណប័ណ្ណ/សង្គម:',
    'history.detail.disease': 'ជំងឺ/អាឡែស៊ី:',
    'history.detail.service': 'សេវាកម្ម:',
    'history.detail.date': 'កាលបរិច្ឆេទ:',
    'history.detail.time': 'ពេលវេលា:',
    'history.detail.note': 'កំណត់ចំណាំ:',
    'history.detail.status': 'ស្ថានភាព:',
    'history.confirm': 'បញ្ជាក់',
    'history.cancel': 'បោះបង់',
    'history.confirmQ': 'បញ្ជាក់รายการនេះ?',
    'history.cancelQ': 'បោះបង់รายการនេះ?',
    'history.success': 'ប្រតិបត្តិការបានជោគជ័យ',
    'history.error': 'មានបញ្ហា',
    'confirm.title': 'គ្រប់គ្រងការណាត់ជួប',
    'confirm.success': 'ជោគជ័យ!',
    'confirm.error': 'បញ្ហា',
    'confirm.loading': 'ដំណើរការ...',
    'confirm.resultSuccess': 'ប្រតិបត្តិការបានបញ្ចប់',
    'confirm.resultConfirm': 'ការណាត់ជួបត្រូវបានបញ្ជាក់',
    'confirm.resultCancel': 'ការណាត់ជួបត្រូវបានបោះបង់',
    'confirm.btn.confirm': 'បញ្ជាក់',
    'confirm.btn.cancel': 'បោះបង់',
    'confirm.btn.close': 'បិទ',
    'confirm.label.name': 'ឈ្មោះ:',
    'confirm.label.service': 'សេវាកម្ម:',
    'confirm.label.price': 'តម្លៃ:',
    'confirm.label.date': 'កាលបរិច្ឆេទ:',
    'confirm.label.time': 'ពេលវេលា:'
  }
};



